import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import Script from "next/script";
import colors from "tailwindcss/colors";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    themeColor: colors.gray["900"]
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Script
            src="https://kit.fontawesome.com/b76555a198.js"
            strategy="afterInteractive"
            crossOrigin="anonymous"
        />
        <body className={inter.className}>{children}</body>
        </html>
    )
}
